/*
    Copyright (c) 2019 Kwan Tecnología
    THIS IS A PRIVATE USE LICENSE.
    THIS IS NOT AN OPEN SOURCE LICENSE.
    USE IS ONLY ALLOWED FOR PROJECTS PRODUCED FOR CUSTOMER "URGEGAS" BY  
    KWAN TECNOLOGIA S. DE R.L. DE C.V. OR KWAN TECHNOLOGIES INC.  
    PART OF THE CODE INCLUDED IN THIS SOFTWARE IS PROPERTY OF KWAN TECHNOLOGY INC
    AND KWAN TECNOLOGIA S DE RL DE CV AND HAS BEEN GRANTED ROYALTY FREE USE TO CUSTOMER URGEGAS
    ALL OTHER USES MUST FIRST OBTAIN WRITTEN PERMISSION OF EITHER OF THE ABOVE COMPANIES.
    FOR FURTHER INFORMATION CONTACT  
    KWAN TECNOLOGIA  
    www.kwantec.com 
 */

module.exports = require('./src/util/plugin-util')